// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CHC.Consent.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("date-of-birth")]
    public partial class DateOfBirth : IIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the DateOfBirth class.
        /// </summary>
        public DateOfBirth()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DateOfBirth class.
        /// </summary>
        public DateOfBirth(System.DateTime? dateOfBirthProperty = default(System.DateTime?))
        {
            DateOfBirthProperty = dateOfBirthProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateOfBirth")]
        public System.DateTime? DateOfBirthProperty { get; set; }

    }
}
