// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CHC.Consent.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Evidence
    {
        /// <summary>
        /// Initializes a new instance of the Evidence class.
        /// </summary>
        public Evidence()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Evidence class.
        /// </summary>
        public Evidence(long? id = default(long?))
        {
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; private set; }

    }
}
