// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CHC.Consent.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("pregnancy-number.consent.bib4all.bradfordhospitals.nhs.uk")]
    public partial class PregnancyNumberconsentbib4allbradfordhospitalsnhsuk : Identifier
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PregnancyNumberconsentbib4allbradfordhospitalsnhsuk class.
        /// </summary>
        public PregnancyNumberconsentbib4allbradfordhospitalsnhsuk()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PregnancyNumberconsentbib4allbradfordhospitalsnhsuk class.
        /// </summary>
        public PregnancyNumberconsentbib4allbradfordhospitalsnhsuk(string value = default(string))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; private set; }

    }
}
