// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CHC.Consent.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("sex")]
    public partial class Sex : IIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the Sex class.
        /// </summary>
        public Sex()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Sex class.
        /// </summary>
        /// <param name="sexProperty">Possible values include: 'Unknown',
        /// 'Male', 'Female'</param>
        public Sex(string sexProperty = default(string))
        {
            SexProperty = sexProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Male', 'Female'
        /// </summary>
        [JsonProperty(PropertyName = "sex")]
        public string SexProperty { get; set; }

    }
}
