// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CHC.Consent.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("uk.nhs.bradfordhospitals.bib4all.medway.name")]
    public partial class Uknhsbradfordhospitalsbib4allmedwayname : IIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Uknhsbradfordhospitalsbib4allmedwayname class.
        /// </summary>
        public Uknhsbradfordhospitalsbib4allmedwayname()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Uknhsbradfordhospitalsbib4allmedwayname class.
        /// </summary>
        public Uknhsbradfordhospitalsbib4allmedwayname(string firstName = default(string), string lastName = default(string))
        {
            FirstName = firstName;
            LastName = lastName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

    }
}
