// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CHC.Consent.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    [Newtonsoft.Json.JsonObject("uk.nhs.bradfordhospitals.hosptial-id")]
    public partial class UknhsbradfordhospitalshosptialId : IIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the UknhsbradfordhospitalshosptialId
        /// class.
        /// </summary>
        public UknhsbradfordhospitalshosptialId()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UknhsbradfordhospitalshosptialId
        /// class.
        /// </summary>
        public UknhsbradfordhospitalshosptialId(string value = default(string))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; private set; }

    }
}
