// <auto-generated />
using CHC.Consent.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace CHC.Consent.EntityFramework.Migrations.Core
{
    [DbContext(typeof(CoreContext))]
    partial class CoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CHC.Consent.Common.Core.Study", b =>
                {
                    b.Property<int>("StudyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("StudyId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("CHC.Consent.Common.Core.Study", b =>
                {
                    b.OwnsOne("CHC.Consent.Common.Core.StudyIdentifier", "Id", b1 =>
                        {
                            b1.Property<int?>("StudyId");

                            b1.Property<long>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Id");

                            b1.ToTable("Studies");

                            b1.HasOne("CHC.Consent.Common.Core.Study")
                                .WithOne("Id")
                                .HasForeignKey("CHC.Consent.Common.Core.StudyIdentifier", "StudyId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
