// <auto-generated />
using System;
using CHC.Consent.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CHC.Consent.EFCore.Migrations
{
    [DbContext(typeof(ConsentContext))]
    partial class ConsentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.CaseIdentifierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConsentId");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2147483647);

                    b.HasKey("Id");

                    b.HasIndex("ConsentId");

                    b.ToTable("CaseIdentifier");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.ConsentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccessControlListId");

                    b.Property<DateTime>("DateProvided");

                    b.Property<DateTime?>("DateWithdrawn");

                    b.Property<long>("GivenByPersonId");

                    b.Property<long>("StudySubjectId");

                    b.HasKey("Id");

                    b.HasIndex("AccessControlListId")
                        .IsUnique();

                    b.HasIndex("GivenByPersonId");

                    b.HasIndex("StudySubjectId", "DateProvided", "DateWithdrawn")
                        .IsUnique()
                        .HasFilter("[DateWithdrawn] IS NOT NULL");

                    b.ToTable("Consent");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.EvidenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ConsentId")
                        .IsRequired();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2147483647);

                    b.HasKey("Id");

                    b.ToTable("Evidence");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EvidenceEntity");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.StudyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccessControlListId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AccessControlListId")
                        .IsUnique();

                    b.ToTable("Study");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.StudySubjectEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("PersonId");

                    b.Property<long>("StudyId");

                    b.Property<string>("SubjectIdentifier")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("StudyId", "PersonId")
                        .IsUnique();

                    b.HasIndex("StudyId", "SubjectIdentifier")
                        .IsUnique();

                    b.ToTable("StudySubject");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Entities.PersonEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccessControlListId");

                    b.HasKey("Id");

                    b.HasIndex("AccessControlListId")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Entities.PersonIdentifierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<long?>("PersonId")
                        .IsRequired();

                    b.Property<string>("TypeName")
                        .IsRequired();

                    b.Property<string>("Value")
                        .HasMaxLength(2147483647);

                    b.Property<string>("ValueType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonIdentifier");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Entities.SubjectIdentifierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccessControlListId");

                    b.Property<long>("CurrentValue");

                    b.Property<long>("StudyId");

                    b.HasKey("Id");

                    b.HasIndex("AccessControlListId")
                        .IsUnique();

                    b.HasIndex("StudyId");

                    b.ToTable("SubjectIdentifiers");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.AccessControlEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccessControlListId");

                    b.Property<long>("PermissionId");

                    b.Property<long>("SecurityPrincipalId");

                    b.HasKey("Id");

                    b.HasIndex("AccessControlListId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("SecurityPrincipalId");

                    b.ToTable("AccessControl");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.AccessControlList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("AccessControlList");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.ConsentRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<long?>("ParentRoleId");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.ConsentUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.PermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.SecurityPrinicipal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SecurityPrinicipal");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SecurityPrinicipal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<long>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.GivenEvidenceEntity", b =>
                {
                    b.HasBaseType("CHC.Consent.EFCore.Consent.EvidenceEntity");


                    b.HasIndex("ConsentId");

                    b.ToTable("GivenEvidenceEntity");

                    b.HasDiscriminator().HasValue("Given");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.WithdrawnEvidenceEntity", b =>
                {
                    b.HasBaseType("CHC.Consent.EFCore.Consent.EvidenceEntity");


                    b.HasIndex("ConsentId")
                        .HasName("IX_Evidence_ConsentId1");

                    b.ToTable("WithdrawnEvidenceEntity");

                    b.HasDiscriminator().HasValue("Withdrawn");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.RoleSecurityPrincipal", b =>
                {
                    b.HasBaseType("CHC.Consent.EFCore.Security.SecurityPrinicipal");

                    b.Property<long>("ConsentRoleId");

                    b.HasIndex("ConsentRoleId")
                        .IsUnique()
                        .HasFilter("[ConsentRoleId] IS NOT NULL");

                    b.ToTable("RoleSecurityPrincipal");

                    b.HasDiscriminator().HasValue("RoleSecurityPrincipal");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.UserSecurityPrincipal", b =>
                {
                    b.HasBaseType("CHC.Consent.EFCore.Security.SecurityPrinicipal");

                    b.Property<long>("ConsentUserId");

                    b.HasIndex("ConsentUserId")
                        .IsUnique()
                        .HasFilter("[ConsentUserId] IS NOT NULL");

                    b.ToTable("UserSecurityPrincipal");

                    b.HasDiscriminator().HasValue("UserSecurityPrincipal");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.CaseIdentifierEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Consent.ConsentEntity", "Consent")
                        .WithMany("CaseIdentifiers")
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.ConsentEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.AccessControlList", "ACL")
                        .WithOne()
                        .HasForeignKey("CHC.Consent.EFCore.Consent.ConsentEntity", "AccessControlListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHC.Consent.EFCore.Entities.PersonEntity", "GivenBy")
                        .WithMany()
                        .HasForeignKey("GivenByPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CHC.Consent.EFCore.Consent.StudySubjectEntity", "StudySubject")
                        .WithMany()
                        .HasForeignKey("StudySubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.StudyEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.AccessControlList", "ACL")
                        .WithOne()
                        .HasForeignKey("CHC.Consent.EFCore.Consent.StudyEntity", "AccessControlListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.StudySubjectEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Entities.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHC.Consent.EFCore.Consent.StudyEntity", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Entities.PersonEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.AccessControlList", "ACL")
                        .WithOne()
                        .HasForeignKey("CHC.Consent.EFCore.Entities.PersonEntity", "AccessControlListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Entities.PersonIdentifierEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Entities.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Entities.SubjectIdentifierEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.AccessControlList", "ACL")
                        .WithOne()
                        .HasForeignKey("CHC.Consent.EFCore.Entities.SubjectIdentifierEntity", "AccessControlListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHC.Consent.EFCore.Consent.StudyEntity")
                        .WithMany()
                        .HasForeignKey("StudyId");
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.AccessControlEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.AccessControlList", "ACL")
                        .WithMany("Entries")
                        .HasForeignKey("AccessControlListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHC.Consent.EFCore.Security.PermissionEntity", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHC.Consent.EFCore.Security.SecurityPrinicipal", "Prinicipal")
                        .WithMany("Access")
                        .HasForeignKey("SecurityPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.ConsentRole", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentRole", "ParentRole")
                        .WithMany()
                        .HasForeignKey("ParentRoleId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CHC.Consent.EFCore.Security.ConsentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.GivenEvidenceEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Consent.ConsentEntity", "Consent")
                        .WithMany("GivenEvidence")
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Consent.WithdrawnEvidenceEntity", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Consent.ConsentEntity", "Consent")
                        .WithMany("WithdrawnEvidence")
                        .HasForeignKey("ConsentId")
                        .HasConstraintName("FK_Evidence_Consent_ConsentId1")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.RoleSecurityPrincipal", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentRole", "Role")
                        .WithOne("Principal")
                        .HasForeignKey("CHC.Consent.EFCore.Security.RoleSecurityPrincipal", "ConsentRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CHC.Consent.EFCore.Security.UserSecurityPrincipal", b =>
                {
                    b.HasOne("CHC.Consent.EFCore.Security.ConsentUser", "User")
                        .WithOne("Principal")
                        .HasForeignKey("CHC.Consent.EFCore.Security.UserSecurityPrincipal", "ConsentUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
